CREATE TABLE IF NOT EXISTS mpa (
    mpa_id int generated by default as identity NOT NULL PRIMARY KEY,
    name varchar(64)
);

CREATE TABLE IF NOT EXISTS films (
    film_id int generated by default as identity NOT NULL PRIMARY KEY,
    name varchar(64),
    description varchar(200),
    release_date date,
    duration int,
    mpa_id int REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS users (
    user_id int generated by default as identity NOT NULL PRIMARY KEY,
    name varchar(64),
    email varchar(64),
    login varchar(64),
    birthday date
);

CREATE TABLE IF NOT EXISTS likes (
    user_id int,
    film_id int
);

CREATE TABLE IF NOT EXISTS friends (
    user_id1 int,
    user_id2 int,
    approved boolean
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id int PRIMARY KEY,
    name varchar(64)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  int,
    genre_id int REFERENCES genres (genre_id)
);